[project]
name = "sgr-agent-erc32"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "litellm>=1.80.7",
    "smolagents>=1.23.0",
]
